name: Test
on:
  push:
    paths:
      - '**.js'
      - '**.html'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright (for browser testing)
        run: |
          npm init -y
          npm install playwright
          echo "installing browser stuff"

      - name: Run Browser Tests
        run: |
          if [ -f index.js ]; then
            node <<EOF
            const { chromium } = require('playwright');
            (async () => {
              const browser = await chromium.launch();
              const page = await browser.newPage();
              await page.goto('file://${GITHUB_WORKSPACE}/index.html');
              await page.addScriptTag({ path: 'index.js' });
              console.log("no errors - browser loaded your hilarious code");
              await browser.close();
            })();
            EOF
          else
            echo "no errors"
          fi
